### ISSUE TITLE
Consider moving to log/slog

### ISSUE THREAD

**Issue by navamedha** [mcosta74/pgx-slog#2]
Now that slog is available as `log/slog`, can we consider moving from `golang.org/x/exp/slog` to `log/slog` ?

**Comment by mcosta74** [comment]
Hi @navamedha, I'll move to `log/slog` as soon as go `v1.22` will be released (Go 1.20 will go out of support). 

Since `log/slog` has been released with Go v1.21, I want this package working also for who is using Go v1.20
